# **Activity A**

In [1]:
#LAB 1:Welcome to Machine Learning
#Name: Nafisa Akter
#ID: 20245103042

print("Hello, future ML detective!")
print("Rule 1: The computer is literal, not rude.")

Hello, future ML detective!
Rule 1: The computer is literal, not rude.

# **Activity B**

In [2]:
import numpy as np
np.random.seed(42)
marks = np.array([55, 72, 48, 90, 66, 81])
print('Marks:', marks)
print('Mean:', marks.mean())
print('Highest:', marks.max())
print('Passed:', marks[marks >= 50])

#12
print('\nLowest:', marks.min())
print('Standard Deviation:',marks.std())
#13
bonus_marks=marks+5
print('Marks with 5 bonus marks:',bonus_marks)
#14
passed_students_count=np.sum(marks>=50)
print('Number of passed students:',passed_students_count)
#15
marks_matrix=marks.reshape(2,3)
print('Marks as a 2x3 matrix:\n',marks_matrix)

Marks: [55 72 48 90 66 81]
Mean: 68.66666666666667
Highest: 90
Passed: [55 72 90 66 81]

Lowest: 48
Standard Deviation: 14.372040758206733
Marks with 5 bonus marks: [60 77 53 95 71 86]
Number of passed students: 5
Marks as a 2x3 matrix:
 [[55 72 48]
 [90 66 81]]

# **Activity C**

In [9]:
import pandas as pd

data = {
'student': ['Asha', 'Babu', 'Chayan', 'Dipa', 'Emon', 'Farah'],
'study_hours': [2, 5, 1, 7, 3, 6],
'sleep_hours': [8, 6, 9, 5, 7, 6],
'attendance': [70, 88, 55, 95, 75, 91],
'snacks': [3, 2, 5, 1, 4, 2],
'passed': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)
display(df)
print(df.info())

#16
print("\nFeatures: 'study_hours', 'sleep_hours', 'attendance', 'snacks'")
print("Label: 'passed'")
#17
print("\nNumber of samples:", df.shape[0])
print("Number of columns:", df.shape[1])
#18
print("\nFiltered Students:")
filtered_students = df[df['attendance'] >= 80]
display(filtered_students)
#19
passed_students_study_hours = df[df['passed'] == 'Yes']['study_hours'].mean()
print(f"\nAverage study hours for students who passed: {passed_students_study_hours:.2f} hours")
#20
print("\nSorted DataFrame by Attendance (Descending):")
sorted_df = df.sort_values(by='attendance', ascending=False)
display(sorted_df)
#21
print("\nNo, this tiny dataset does not prove that snack purchases cause failure.")

  student  study_hours  sleep_hours  attendance  snacks passed
0    Asha            2            8          70       3    Yes
1    Babu            5            6          88       2    Yes
2  Chayan            1            9          55       5     No
3    Dipa            7            5          95       1    Yes
4    Emon            3            7          75       4     No
5   Farah            6            6          91       2    Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student      6 non-null      object
 1   study_hours  6 non-null      int64
 2   sleep_hours  6 non-null      int64
 3   attendance   6 non-null      int64
 4   snacks       6 non-null      int64
 5   passed       6 non-null      object
dtypes: int64(4), object(2)
memory usage: 420.0+ bytes
None

Features: 'study_hours', 'sleep_hours', 'attendance', 'snacks'
Label: 'passed'

Number of samples: 6
Number of columns: 6

Filtered Students:

  student  study_hours  sleep_hours  attendance  snacks passed
1    Babu            5            6          88       2    Yes
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes

Average study hours for students who passed: 5.00 hours

Sorted DataFrame by Attendance (Descending):

  student  study_hours  sleep_hours  attendance  snacks passed
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes
1    Babu            5            6          88       2    Yes
4    Emon            3            7          75       4     No
0    Asha            2            8          70       3    Yes
2  Chayan            1            9          55       5     No

No, this tiny dataset does not prove that snack purchases cause failure.

# **Activity D**

In [12]:
import random
import numpy as np

def generate_scores(use_seed):
 if use_seed:
  random.seed(45)
  np.random.seed(45)
 return np.random.randint(40, 101, size=5)

print('Seeded run 1:', generate_scores(True))
print('Seeded run 2:', generate_scores(True))
print('Unseeded run 1:', generate_scores(False))
print('Unseeded run 2:', generate_scores(False))

print("No, it is not fair to directly compare the model accuracies if two groups used different random splits.")
print("Different random splits mean the models were tested on different data,")
print("so the accuracy difference may be caused by the split rather than the model itself.")
print("For a fair comparison, both groups should use the same random seed/split, ")
print("or use the same cross-validation procedure.")

Seeded run 1: [ 51  70  43 100  72]
Seeded run 2: [ 51  70  43 100  72]
Unseeded run 1: [71 61 75 44 97]
Unseeded run 2: [96 55 41 54 93]
No, it is not fair to directly compare the model accuracies if two groups used different random splits.
Different random splits mean the models were tested on different data,
so the accuracy difference may be caused by the split rather than the model itself.
For a fair comparison, both groups should use the same random seed/split,
or use the same cross-validation procedure.

# **Activity E**

**1. Problem**

Question: What decision or prediction is needed?

Answer: The problem is to predict whether a student will pass or fail based on study hours, sleep hours, attendance, and snack purchases.

**2. Data**

Question: Is the dataset relevant, legal, and
documented?

Answer: The dataset contains relevant student information such as study hours, sleep hours, attendance, snacks, and pass/fail status. The dataset source should be documented before using it.

**3. Preparation**

Question: Are values missing, duplicated, biased, or leaked?

Answer: The dataset was loaded into a Pandas DataFrame. Data inspection was performed using info() and describe(). No missing values or duplicates were observed in this small dataset.

**4. Baseline**

Question: What simple method sets the minimum
standard?

Answer: A simple baseline could be predicting the most common class or using a basic classification model.

**5. Evaluation**

Question: Which metric matches the real cost of errors?

Answer: Accuracy can be used because the task is to classify students as passed or failed.

**6. Improvement**

Question: What unique contribution is being tested?

Answer: Possible improvements include collecting more data, adding new features, or testing different machine learning algorithms.

**7. Communication

Question: Can another person reproduce and understand it?

Answer: The notebook should contain code, outputs, explanations, and observations so another person can reproduce the results.